# Generated by Django 4.2.2 on 2024-08-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='houses',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='village',
            name='monestaries',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='village',
            name='populations',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='village',
            name='schools',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
