# Generated by Django 4.2.2 on 2024-08-21 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_village_houses_village_monestaries_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('township', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.township')),
            ],
        ),
    ]
