# Generated by Django 4.2.2 on 2024-08-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='houses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='monestaries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='schools',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
