# Generated by Django 5.1 on 2024-10-04 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_schooltype_alter_village_houses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='houses',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='monestaries',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='populations',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='schools',
            field=models.IntegerField(blank=True),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachers', models.IntegerField()),
                ('students', models.IntegerField()),
                ('school_type', models.ManyToManyField(to='myapp.schooltype')),
                ('villages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.village')),
            ],
        ),
    ]
