# Generated by Django 5.1 on 2024-10-04 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_village_houses_alter_village_monestaries_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='school_type',
            new_name='name',
        ),
    ]
