# Generated by Django 5.1 on 2024-10-04 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_school_type_school_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='students',
        ),
        migrations.RemoveField(
            model_name='school',
            name='teachers',
        ),
    ]
