# Generated by Django 5.1 on 2024-10-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_school_students_remove_school_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_types',
            field=models.ManyToManyField(to='myapp.schooltype'),
        ),
        migrations.RemoveField(
            model_name='school',
            name='name',
        ),
        migrations.AddField(
            model_name='school',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
